pwa:
    image_processor: SpomkyLabs\PwaBundle\ImageProcessor\GDImageProcessor

    manifest:
        background_color: '#ffffff'
        description: Gestion de ma collection de BD et comics
        display: standalone
        enabled: true
        icons:
            - sizes: [192]
              src: images/icon-192.png
            - sizes: [512]
              src: images/icon-512.png
        lang: fr
        name: Ma Bibliotheque BD
        public_url: /manifest.webmanifest
        short_name: BibliotheQue
        start_url:
            path: /
        theme_color: '#1976d2'

    serviceworker:
        dest: /sw.js
        enabled: true
        scope: /
        skip_waiting: true
        workbox:
            clear_cache: false

            asset_cache:
                cache_name: bibliotheque-assets
                enabled: true
                max_age: 31536000

            cache_manifest: true

            google_fonts:
                cache_prefix: google-fonts
                enabled: true
                max_age: 31536000
                max_entries: 30

            image_cache:
                cache_name: bibliotheque-images
                enabled: true
                max_age: 31536000
                max_entries: 60

            offline_fallback:
                page:
                    path: app_offline

            resource_caches:
                - cache_name: bibliotheque-api
                  match_callback: '/\/api\//'
                  network_timeout: 3
                  strategy: NetworkFirst

                - cache_name: bibliotheque-libs
                  match_callback: '({url}) => url.pathname.startsWith("/workbox/") || url.pathname.startsWith("/idb/")'
                  strategy: CacheFirst

                - cache_name: bibliotheque-pages
                  match_callback: '({request}) => request.mode === "navigate"'
                  network_timeout: 3
                  strategy: NetworkFirst
