framework:
    messenger:
        failure_transport: failed
        routing:
            App\Message\DownloadCoverMessage: async
            App\Message\EnrichSeriesMessage: async
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: false
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed:
                dsn: 'doctrine://default?queue_name=failed'
                options:
                    auto_setup: false
