framework:
    rate_limiter:
        gemini_api:
            interval: '1 minute'
            limit: 20
            policy: sliding_window
        dev_login:
            interval: '1 minute'
            limit: 5
            policy: sliding_window
        google_login:
            interval: '1 minute'
            limit: 10
            policy: sliding_window
