framework:
    rate_limiter:
        api_lookup:
            interval: '1 minute'
            limit: 30
            policy: sliding_window
        cover_search:
            interval: '1 minute'
            limit: 20
            policy: sliding_window
        gemini_api:
            interval: '1 minute'
            limit: 20
            policy: sliding_window
        google_login:
            interval: '1 minute'
            limit: 10
            policy: sliding_window
