services:
  chrome:
    container_name: ddev-${DDEV_SITENAME}-chrome
    image: seleniarm/standalone-chromium:latest
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_VNC_NO_PASSWORD=1
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    expose:
      - "4444"
      - "7900"
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
    networks:
      - default
      - ddev_default
